Feature/milestone friendship v1
jpdf00/ror-social-scaffold pull request #3
Opened 2021-03-12 17:41 UTC by jpdf00

This milestone adds friendship functionality:
- Users are able to send friendship invitations to other users (but only once, and not to themselves).
- Users see a button “Invite to friendship” next to the name of the user who is not their friend yet - on both users’ list and single-user page.
- Users are able to see pending friendship invitations sent to them from other users.
- Users are able to accept or reject friendship invitations sent to them.

2021-03-12 22:26 UTC, GzimAsani requested changes
# Status: Changes Required :red_circle: 

### Hello **team**, first of all I apologize for the time you waited for this review. I had difficulties running your migrations and this was my problem. Unfortunately I was not able to review your app completely I can only say that user/friendship model is looking  good and so far I can only suggest you to do the following:
- [ ] Add  Unit and Integration tests!  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] There should not be any logic in the views because the latter is used only for rendering. Please move all your logic from your views and add it in your helpers.
- [ ] You have rubocop offenses locally, kindly fix them

Please do those required changes and ask for another code review where the next reviewer can check your app layouts and its functionality.

_**If you have any question related to the required changes feel free to text me on slack @GzimAsani** or just add a comment here_

HAPPY CODING :computer: :desktop_computer:

2021-03-16 16:37 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello @jpdf00  and @anapdh, 

You've done well so far 👍 and I commend you for that 👏
However, there are still some changes to be made before this milestone can be approved.

- [ ] @anapdh your commit messages should be capitalized. You can watch this [video](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6) on how to edit your commit messages using git rebase
 See [Git Commit Best Practices](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) for more insights

- [x] User should be able to invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [ ] User should be able to see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [ ] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [ ] There should be a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [ ] Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [ ] It's not really a good idea boxing all your unit tests into one single file. Let's keep organize and professional. You can create a model folder inside the spec directory, and let each model have their on spec file. Same for integration tests.

- [ ] There should be NO application logic in the views nor helpers (no Post.new, Comment.create, current_user.friends.find_by(...)...). Everything connected with data processing should be encapsulated in models and used in controllers. I have made some comments on the affected method in your codebase below.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-16 16:37 UTC, acushlakoncept commented on spec/integration_spec.rb
> +# end
It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
See this [post](https://stackoverflow.com/questions/13130859/inline-comments-in-ruby/13130900#:~:text=No%2C%20Ruby%20does%20not%20have,comment%20out%20the%20one%20row), about why comments are discouraged.

2021-03-16 16:37 UTC, acushlakoncept commented on spec/models_spec.rb
> +      expect(post).to_not be_valid
You save some lines by simple using `times` method to generate your 1000 charater string
```ruby
str = ' '
1000.times { str << 'a' }
post.content = str
```

2021-03-16 16:37 UTC, acushlakoncept commented on app/helpers/user_helper.rb
> +                                                                               )).exists?
you should never use the `where` method, or any other query-building methods like this, outside of the model class itself, Take a look at this article for more Ruby on Rails best practices: [Buggy Rails Code: The 10 Most Common Mistakes That Rails Developers Make](https://www.toptal.com/ruby-on-rails/top-10-mistakes-that-rails-programmers-make)

2021-03-16 23:10 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [x] This should have its own page, assuming I had a thousand posts I have to scroll all the way down 
![Screenshot from 2021-03-16 23-56-51](https://user-images.githubusercontent.com/23278161/111390750-8eeb8600-86b3-11eb-82d8-d1dfe72a8d48.png)
- [x] Kindly separate your test into files it looks more organised and professional.

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2021-03-17 19:21 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED✔✔✔✔**

Great  implementation of the project. 
You can merge👏👏👏

Happy coding💻💻

2021-03-17 19:54 UTC, merged